version: 0.0
os: linux
files:
  - destination: ./
    source: ./
hooks:
  AfterInstall:
    - location: ./scripts/install_dependencies.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: ./scripts/start_server.sh
      timeout: 100
      runas: root