version: 0.0
os: linux
files:
  - destination: /back-scratch
    source: ./
hooks:
  Install:
    - location: /scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/start_server.sh
      timeout: 1000
      runas: root