version: 0.0
os: linux
files:
  - destination: ./home/ec2-user
    source: ./
hooks:
  Install:
    - location: ./scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/start_server.sh
      timeout: 10000
      runas: root